wiki/encyclopedia/urls.py
# from django import urls
from django.urls import path

from . import views
app_name = "encyclopedia"
urlpatterns = [
    path("", views.index, name="index"),
    path("wiki/search",views.search, name= "search"),
    path("wiki/create_entry", views.create_entry, name="create_entry"),
    path("<str:title>", views.view_entry, name='view_entry'),
    path("wiki/edit_entry/<str:title>", views.edit_entry, name="edit_entry"),
    path("wiki/save_and_view",views.save_and_view, name = "save_and_view"),
    path("wiki/random_page",views.random_page,name = "random_page")
    
    # path("create_entry",)
    
]

wiki/wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

wiki/encyclopedia/models.py
from django.db import models

# Create your models here.

wiki/encyclopedia/views.py
from django.urls import reverse
from django.shortcuts import redirect, render
from django.http import HttpResponse,HttpResponseRedirect
from . import markdown_interpreter as interpreter
from . import util
from . import functions
from random import choice
def index(request):
    try:
        notification = request.notification
        print(request.notification)
    except AttributeError:
        notification = None
        pass
    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries(),
        "notification" : notification
    })
def view_entry(request,title):
    string = util.get_entry(title)
    if string == None:
        available_entry = util.list_entries()
        suggestion = functions.generate_suggestion(available_entry,title,True)
        
        return render(request, "encyclopedia/404.html",{
            "title": title,
            "options": suggestion
        })
        
    string_html = interpreter.convert_to_html(string = string)
    
    return render(request,"encyclopedia/entry.html",{
        "contents": string_html,
        "entry": title
    })

def search(request):
    query = request.GET['q']
    return view_entry(request,query)

def edit_entry(request,title):
    string = util.get_entry(title)
    return create_entry(request,initial_content=string, title=title)
                  

def create_entry(request, initial_content="",title=""):
    return render(request,'encyclopedia/create_entry.html',{
        "purpose" : "create",
        "title": title,
        "initial_content": initial_content
    })
    
def random_page(request):
    entries = util.list_entries()
    random_entry = choice(entries)
    # return HttpResponse(reverse(random_entry))
    return redirect("/"+random_entry)

def save_and_view(request):
    if request.method == "POST":
        title = request.POST['title']
        summary = request.POST['summary']
        content = request.POST['content']
        util.save_entry(title,content)
        request.notification = "Operation was successful"
        return redirect(f"/{title}")
    request.notification = "Sorry Your request Wasn't saved successfully \
        Please go to the official create page to create your entry"
    # return redirect('/')
    return HttpResponseRedirect(reverse('index'))

wiki/encyclopedia/templates/encyclopedia/create_entry.html
{% extends "encyclopedia/layout.html" %} 
{% load static %}
    {% block title %} 
        Encyclopedia 
    {%endblock %} 
   
{% block body %}
<h1>
   {{purpose}} your page using markdown
</h1>
<form action="{%url 'encyclopedia:save_and_view' %}" method="POST">
    {% csrf_token %}
    <div class="breadcrumb content">
        <div class="breadcrumb content">
            <label for="TITLE">Title:</label>
            <input id="TITLE" name='title' type='text' value="{{title}}" />
        </div>
    </div>
    <div class="breadcrumb content">
        <b class="breadcrumb-item badge-info">Optional :: </b>
        <textarea
            class="breadcrumb-item"
            name="summary"
            rows="2"
            cols="50"
            style="max-width:100%; max-height:100px"
            placeholder="Give a summary of this page"
        ></textarea>
    </div>
    <div class="breadcrumb content">
        <b class="breadcrumb-item badge-info">Your Entry::</b>
        <textarea
            class="breadcrumb-item"
            name="content"
            rows="5"
            cols="400"
            style="max-width:100%;"
            placeholder="Create your page with easy markdown language and it will be converted for you "
        >{{initial_content}}</textarea>
        
        <button class="btn btn-outline-info" name="submit" action="submit">
            Save and View Page
        </button><br/>
        <p>For tutorial on how to use this tool see <a href="#">wiki/tutorials</a><p>
    </div>
</form>
<script>
    // document.getElementById('TITLE').value = "{{title}}"
</script>
{% endblock %}

wiki/encyclopedia/templates/encyclopedia/entry.html
{% extends "encyclopedia/layout.html" %} 
    
{% block title %} 
        {{entry}} 
{% endblock %} 
{% block body %}
"{% autoescape off %}"
   <p id="contents"> {{contents|linebreaks}}  </p>
   "{% endautoescape %}"
    <br>
    
        <a class="btn btn-outline-secondary" href ="{% url 'encyclopedia:edit_entry' entry %}" id="edit" >Edit This Page</a>
<script>
    // let paragraph = document.getElementById("contents")

    // paragraph.textContent ="{{contents|linebreaks}}"
    
</script>
{% endblock %}

wiki/encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %} 
{% load static %}
    {% block title %} 
        Encyclopedia 
    {%endblock %} 
   
{% block body %}

<h1>All Pages</h1>

<ul >
    {% for entry in entries %}
        <li class="entry_list"><a class = "entries" href = "{{entry}}">{{ entry }}</a></li>
    {% endfor %}
</ul>
<script>
    anchors = document.getElementsByClassName('entries')
    if ("{{notification}}" != "None"){
        alert("{{notification}}")
    }

</script>

{% endblock %}

wiki/encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <!-- <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous"> -->
        <link rel="stylesheet" href="{% static 'encyclopedia/bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'encyclopedia/bootstrap.min.js' %}">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
        <link rel="stylesheet" href="{% static 'encyclopedia/style2.css' %}">
        <script src="{% static 'encyclopedia/scripts.js' %}" ></script>
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form action = "{% url 'encyclopedia:search' %}">
                    <input class="search" onkeyup = "show_suggestions()"
                     type="text" name="q" placeholder="Search Encyclopedia">
                </form>
                <div class = "nav-button">
                    <a  href="{% url 'encyclopedia:index' %}">Home</a>
                </div>
                <div  class = "nav-button">
                    <a href = "{% url 'encyclopedia:create_entry' %}">Create New Page</a>
                </div>
                <div class = "nav-button">
                    <a  href = "{% url 'encyclopedia:random_page' %}">Random Page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>
    </body>
</html>